name: flutter_application_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  font_awesome_flutter: ^10.9.1
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  intl: ^0.20.2
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
